### ISSUE TITLE
Can (expreg-expand) expand reliably across languages? From CSS to parent HTML?

### ISSUE THREAD

**Issue by Dima-369** [casouri/expreg#3]
Say, I have this HTML with `treesit-language-at-point-function` setup correctly to return `'html` or `'css`:

```html
 <html>
   <head>
     <style>
      body {
        background: url("/background.png");
        color: #ff0000;
      }
     </style>
   </head>
 </html>
```

If I place my cursor on `background` and call `(expreg-expand)`, I notice that it gets stuck at this place, regardless how many times I call. It seems to have issues marking the outer HTML as well. 

Is this not implemented yet, or a possible bug?

![CleanShot 2023-09-15 at 21 30 17](https://github.com/casouri/expreg/assets/15002298/9fe47442-4597-414d-a834-83fbe597c84c)

Thanks!

**Comment by casouri** [comment]
Right. It wasn't implemented. I just added support for multi-language buffers, please see it works well :-)

**Comment by Dima-369** [comment]
Hey, thanks for the quick adjustment! My example above works great now. I also tested with basic Javascript in the buffer and it also worked out.

So I tested with an even more file file with PHP+HTML/CSS/JS and there I still see it breaking. If I start on `background` in CSS or if I start on `is_array` in PHP, the marked region ends up incorrectly spanning different elements.


https://github.com/casouri/expreg/assets/15002298/3906382a-ce62-4acc-bf74-567cbdefffb3

I wonder if it is about my language at point function?

```emacs-lisp
(defun dima-php-ts-treesit-language-at-point (point)
  "Return the language at point which can be 'php 'html 'css or 'javascript."
  (let ((php-node (treesit-node-at (point) 'php)))
    (cond
     ((string= "text" (treesit-node-type php-node))
      (let ((html-type (treesit-node-type (treesit-node-at (point) 'html))))
        (if (string= "raw_text" html-type)
            (let ((cssp (treesit-parent-until
                         (treesit-node-at (point) 'html)
                         (lambda (node)
                           (string= "style_element" (treesit-node-type node))))))
              (if cssp
                  'css
                (let ((javascriptp (treesit-parent-until
                                    (treesit-node-at (point) 'html)
                                    (lambda (node)
                                      (string= "script_element" (treesit-node-type node))))))
                  (if javascriptp
                      'javascript
                    'html))))
          'html)))
     (t
      'php))))
```

```json
<html lang="en-gb">
   <head>
     <style type="text/css">
      body {
        background: url("/background.png");
        color: #ff0000;
      }
     </style>
   </head>

   <body>
     <?php
     $a = [1, 2, "3", 4.5];
     if (is_array($a)) {
       echo "$a is an array";
     } else {
       echo "$a is not an array";
     }
     ?>

   </body>
 </html>
```

**Comment by casouri** [comment]
Ah, I figure it won't be this easy ;-) It's probably not tree-sitter expander breaking, but some other expander, do you mind setting `expreg--verbose` to t and try your example again? You should see which expander is responsible for each expand. It would also be good if you can share the major mode you are using, so that I can try out myself, too.

**Comment by Dima-369** [comment]
With my last PHP code example, I place the point on `body` in the CSS, then I call `expreg-expand` twice. This is the outcome:

![CleanShot 2023-09-16 at 09 12 22](https://github.com/casouri/expreg/assets/15002298/5114938e-5e23-4bd6-80bd-2323e99d807b)

This gets logged from `expreg--verbose`, looks really weird with the different languages.

```bash
blame: word--within-space
next: ((word--symbol 66 . 70) (word--plain 66 . 70) (treesit--css 66 . 70) (treesit--javascript 66 . 70) (treesit--css 12 . 70) (treesit--html 66 . 154) (treesit--html 36 . 162) (treesit--javascript 36 . 162) (treesit--css 12 . 148) (treesit--html 24 . 173) (treesit--javascript 24 . 173) (treesit--php 1 . 190) (treesit--html 1 . 362) (treesit--javascript 1 . 362))
prev: ((word--within-space 66 . 70))

blame: treesit--css
next: ((treesit--html 66 . 154) (treesit--html 36 . 162) (treesit--javascript 36 . 162) (treesit--css 12 . 148) (treesit--html 24 . 173) (treesit--javascript 24 . 173) (treesit--php 1 . 190) (treesit--html 1 . 362) (treesit--javascript 1 . 362))
prev: ((treesit--css 12 . 70) (treesit--javascript 66 . 70) (treesit--css 66 . 70) (word--plain 66 . 70) (word--symbol 66 . 70) (word--within-space 66 . 70))
```

> It would also be good if you can share the major mode you are using, so that I can try out myself, too.

```emacs-lisp
(defun dima-php-ts-treesit-language-at-point (point)
  "Return the language at point which can be 'php 'html 'css or 'javascript."
  (let ((php-node (treesit-node-at (point) 'php)))
    (cond
     ((string= "text" (treesit-node-type php-node))
      (let ((html-type (treesit-node-type (treesit-node-at (point) 'html))))
        (if (string= "raw_text" html-type)
            (let ((cssp (treesit-parent-until
                         (treesit-node-at (point) 'html)
                         (lambda (node)
                           (string= "style_element" (treesit-node-type node))))))
              (if cssp
                  'css
                (let ((javascriptp (treesit-parent-until
                                    (treesit-node-at (point) 'html)
                                    (lambda (node)
                                      (string= "script_element" (treesit-node-type node))))))
                  (if javascriptp
                      'javascript
                    'html))))
          'html)))
     (t
      'php))))

(define-derived-mode test-php-ts-mode fundamental-mode "PHP"
  "Major mode for editing PHP files, using the treesit library."
  (when (treesit-ready-p 'php)
    (treesit-parser-create 'php)
    (treesit-parser-create 'html)
    (treesit-parser-create 'css)
    (treesit-parser-create 'javascript)

    (setq-local treesit-language-at-point-function #'dima-php-ts-treesit-language-at-point)
    (setq-local expreg--verbose t)
    (setq-local treesit-range-settings
                (treesit-range-rules
                 :embed 'html
                 :host 'php
                 '((text_interpolation (text) @capture))

                 :embed 'css
                 :host 'html
                 '((style_element (raw_text) @capture))

                 :embed 'javascript
                 :host 'html
                 '((script_element (raw_text) @capture))))
    

    (treesit-major-mode-setup)))

```

**Comment by Dima-369** [comment]
I also noticed that the font lock behaves incorrectly in this PHP + other languages scenario. Might it all be related in the end?

See this picture from my video above.

![CleanShot 2023-09-16 at 13 52 58](https://github.com/casouri/expreg/assets/15002298/6e6544e1-258f-4a28-b244-7d5e8d7da80d)

Even though, I use `:language php` and `:language css` in my `treesit-font-lock-rules`, I get the feeling that internally they somewhat clash, maybe the languages overlap?

Since I notice a different font lock outcome when I swap my font lock rules around, and they should work language-scoped, I highly suspect a bigger issue here.

**Comment by casouri** [comment]
It very well might be, but I couldn't debug it without a way to reproduce it. So please show me your code. In the meantime, did you set `treesit-range-settings` for your major mode?

**Comment by casouri** [comment]
Thanks. There are two things. Your range query for html should be `'((text) @capture)`, and there's a bug in Emacs that sets the range of an embedded language to the whole buffer when the language doesn't appear in the buffer. In your case, there's no javascript in the buffer, so its range is set to the whole buffer.

The Emacs bug should be fixed in Emacs 29.2, whenever it comes out. Before that, use this workaround:

Define this function
```elisp
(defun test-php--clean-up-parser-range (&rest _)
  (dolist (parser (mapcan (lambda (lang)
                            (treesit-parser-list nil lang))
                          '(html css javascript)))
    (when (null (treesit-parser-included-ranges parser))
      (treesit-parser-set-included-ranges
       parser `(,(point-min) . ,(point-min))))))
```

and add it to the end of `treesit-range-settings`.

```elisp
(setq-local treesit-range-settings
                (treesit-range-rules
                 :embed 'html
                 :host 'php
                 '((text) @capture)

                 :embed 'css
                 :host 'html
                 '((style_element (raw_text) @capture))

                 :embed 'javascript
                 :host 'html
                 '((script_element (raw_text) @capture))

                 #'test-php--clean-up-parser-range))
```

**Comment by Dima-369** [comment]
> The Emacs bug should be fixed in Emacs 29.2, whenever it comes out. 

I am actually running a very recent `master` branch version of `"30.0.50"`, commit: 3ef5f10b190 on macOS.

> Your range query for html should be '((text) @capture)

Hmm, that doesn't seem to fix the bug for me. I can reproduce this on `emacs -Q` with this code (load `expreg.el` before):

It messages that the region is this which is incorrect:

```
"en-gb">
   <head>
     <style type="text/css">
      body
```

```emacs-lisp
(defun dima-php-ts-treesit-language-at-point (point)
  "Return the language at point which can be 'php 'html 'css or 'javascript."
  (let ((php-node (treesit-node-at (point) 'php)))
    (cond
     ((string= "text" (treesit-node-type php-node))
      (let ((html-type (treesit-node-type (treesit-node-at (point) 'html))))
        (if (string= "raw_text" html-type)
            (let ((cssp (treesit-parent-until
                         (treesit-node-at (point) 'html)
                         (lambda (node)
                           (string= "style_element" (treesit-node-type node))))))
              (if cssp
                  'css
                (let ((javascriptp (treesit-parent-until
                                    (treesit-node-at (point) 'html)
                                    (lambda (node)
                                      (string= "script_element" (treesit-node-type node))))))
                  (if javascriptp
                      'javascript
                    'html))))
          'html)))
     (t
      'php))))

(define-derived-mode test-php-ts-mode fundamental-mode "PHP"
  "Major mode for editing PHP files, using the treesit library."
  (when (treesit-ready-p 'php)
    (treesit-parser-create 'php)
    (treesit-parser-create 'html)
    (treesit-parser-create 'css)
    (treesit-parser-create 'javascript)

    (setq-local expreg--verbose t)
    (setq-local treesit-language-at-point-function #'dima-php-ts-treesit-language-at-point)
    (setq-local treesit-range-settings
                (treesit-range-rules
                 :embed 'html
                 :host 'php
                 '((text) @capture)

                 :embed 'css
                 :host 'html
                 '((style_element (raw_text) @capture))

                 :embed 'javascript
                 :host 'html
                 '((script_element (raw_text) @capture))))

    (treesit-major-mode-setup)))

(let ((text "
<html lang=\"en-gb\">
   <head>
     <style type=\"text/css\">
      body {
        background: url(\"/background.png\");
        color: #ff0000;
      }
     </style>
   </head>

   <body>
     <?php
     $a = [1, 2, \"3\", 4.5];
     if (is_array($a)) {
       echo \"$a is an array\";
     } else {
       echo \"$a is not an array\";
     }
     ?>

   </body>
 </html>
"))
  (with-temp-buffer
    (insert text)
    (goto-char (point-min))
    (test-php-ts-mode)
    (search-forward "body")
    (expreg-expand)
    (expreg-expand)
    (message "%s" (buffer-substring-no-properties (region-beginning) (region-end)))))
```

**Comment by casouri** [comment]
> I am actually running a very recent master branch version of "30.0.50", commit: 3ef5f10b190 on macOS.

I haven't even pushed the fix, so the latest master won't help you ;-) Even if I've pushed the fix, bug fixes like that would go to emacs-29 branch first, and then in a few days merged into master. So it'll be a few days before your master build contains that fix.

> Hmm, that doesn't seem to fix the bug for me. I can reproduce this on emacs -Q with this code (load expreg.el before):

That's expected, the query change only fixes part of the problem. The symptom you are seeing is fixed by the workaround I sent you earlier. At least on my machine, it worked flawlessly.

**Comment by Dima-369** [comment]
> I haven't even pushed the fix, so the latest master won't help you ;-) Even if I've pushed the fix, bug fixes like that would go to emacs-29 branch first, and then in a few days merged into master. So it'll be a few days before your master build contains that fix.

Ah, interesting. I didn't know that!

> At least on my machine, it worked flawlessly.

So strange. So I added `#'test-php--clean-up-parser-range` as you mentioned. I still see the exact same bug, regardless if I use `test-php--clean-up-parser-range` or not.

I tested by downloading `expreg.el` and appending the test code from above plus `test-php--clean-up-parser-range` as you mentioned. Here is the full file: 
[expreg.txt](https://github.com/casouri/expreg/files/12642679/expreg.txt) (I can't upload `.el` on GitHub, so I renamed to `.txt)

```bash
emacs --script expreg.txt
```

Do you see the proper result?

For me, it outputs this:

```bash
blame: word--within-space
next: ((word--symbol 67 . 71) (word--plain 67 . 71) (treesit--css 67 . 71) (treesit--javascript 67 . 71) (treesit--css 13 . 71) (treesit--html 67 . 155) (treesit--html 37 . 163) (treesit--javascript 37 . 163) (treesit--css 13 . 149) (treesit--html 25 . 174) (treesit--javascript 25 . 174) (treesit--php 2 . 191) (treesit--html 2 . 363) (treesit--javascript 2 . 363))
prev: ((word--within-space 67 . 71))
blame: treesit--css
next: ((treesit--html 67 . 155) (treesit--html 37 . 163) (treesit--javascript 37 . 163) (treesit--css 13 . 149) (treesit--html 25 . 174) (treesit--javascript 25 . 174) (treesit--php 2 . 191) (treesit--html 2 . 363) (treesit--javascript 2 . 363))
prev: ((treesit--css 13 . 71) (treesit--javascript 67 . 71) (treesit--css 67 . 71) (word--plain 67 . 71) (word--symbol 67 . 71) (word--within-space 67 . 71))
"en-gb">
   <head>
     <style type="text/css">
      body
```

**Comment by casouri** [comment]
Interesting, I got

```
blame: word--within-space
next: ((word--symbol 67 . 71) (word--plain 67 . 71) (treesit--css 67 . 71) (treesit--javascript 60 . 72) (treesit--css 13 . 71) (treesit--html 67 . 155) (treesit--html 37 . 163) (treesit--javascript 37 . 163) (treesit--css 13 . 149) (treesit--html 25 . 174) (treesit--javascript 25 . 174) (treesit--php 2 . 191) (treesit--html 2 . 363) (treesit--javascript 2 . 364))
prev: ((word--within-space 67 . 71))
blame: treesit--javascript
next: ((treesit--css 13 . 71) (treesit--html 67 . 155) (treesit--html 37 . 163) (treesit--javascript 37 . 163) (treesit--css 13 . 149) (treesit--html 25 . 174) (treesit--javascript 25 . 174) (treesit--php 2 . 191) (treesit--html 2 . 363) (treesit--javascript 2 . 364))
prev: ((treesit--javascript 60 . 72) (treesit--css 67 . 71) (word--plain 67 . 71) (word--symbol 67 . 71) (word--within-space 67 . 71))

      body
```

It seems that your css parser is responsible for the error. If you `M-x treesit-explore-mode RET css RET`, what do you see?

For me, I see

```
(stylesheet
 (rule_set
  (selectors (tag_name))
  (block {
   (declaration (property_name) :
    (call_expression (function_name)
     (arguments ( (string_value) )))
    ;)
   (declaration (property_name) :
    (color_value #)
    ;)
   })))
```

which seems about right.

Another idea: try updating all the language grammars to the latest commit.

**Comment by casouri** [comment]
Also, I noticed that you added `ignore-errors` in the workaround. Was there any errors?

**Comment by Dima-369** [comment]
> try updating all the language grammars to the latest commit.

I just did, exact same output for me :(

But your `blame: treesit--javascript` also looks a bit fishy to me. It seems that the CSS and JavaScript regions, overlap, don't they?

> what do you see?

Mine is identical to yours.

> Also, I noticed that you added ignore-errors in the workaround. Was there any errors?

Oh, good catch. I removed it and retested with `emacs --script expreg.txt`, but exact same output.

I noticed that it errors in my 'real' `php-ts-mode` mode but I couldn't really explain it, so disregard it.

---

Just now, I noticed that `treesit-font-lock-settings` get broken when `#'test-php--clean-up-parser-range` is included though.

With `#'test-php--clean-up-parser-range` added, the code below never highlights anything for me in the example code above:

```emacs-lisp
(setq-local treesit-font-lock-settings
                (treesit-font-lock-rules
                 :feature 'keyword
                 :language 'php
                 '((php_tag) @font-lock-keyword-face)))
```

Without it, it looks like this:

![CleanShot 2023-09-18 at 09 07 04](https://github.com/casouri/expreg/assets/15002298/6e6d2394-054a-4748-8624-06024c806c36)

**Comment by Dima-369** [comment]
I just tested with https://emacsformacosx.com/ (Emacs 29.1-1) and I get the exact same buggy behavior as seen above.

![CleanShot 2023-09-18 at 19 09 04](https://github.com/casouri/expreg/assets/15002298/cd6cbbbd-90b8-4753-a2e3-aa1f174f5daf)


What version of Emacs are you using where it works for you?

**Comment by casouri** [comment]
I'm sorry, the workaround I sent you seems to have a typo. It should be

```elisp
(defun test-php--clean-up-parser-range (&rest _)
  (dolist (parser (mapcan (lambda (lang)
                            (treesit-parser-list nil lang))
                          '(html css javascript)))
    (when (null (treesit-parser-included-ranges parser))
      (treesit-parser-set-included-ranges
       parser `((,(point-min) . ,(point-min)))))))
```

That probably explains the error you saw.

Does it work with the updated workaround?

**Comment by Dima-369** [comment]
Oh wow, indeed. It finally works in my 'real' `php-ts-mode`. Font-lock also works, amazing! Thank you 👏 

However, it still fails in the `emacs --script expreg.el` invocation and I just don't understand why, but since it works in my 'real' mode (which only has more customizations), let's finally close this!

**Comment by vpxyz** [comment]
HI,
I'd like to share my [php-ts-mode](https://github.com/vpxyz/php-ts-mode). Thanks to @casouri now character blocking works with html/css/javascript. Imenu and basic indentation also work.
I'm using the latest emacs (created by the master every day) and the latest versions of tree-sitter-php/html/css/javascript.
