### ISSUE TITLE
[BUG]: `expreg-restore-point-on-quit` causes cursor position mess.

### ISSUE THREAD

**Issue by ISouthRain** [casouri/expreg#8]
Setting (setq expreg-restore-point-on-quit t) causes the following issue:

Steps to reproduce:
1. `M-x expreg-expand RET` select text
2. Then scroll the screen with the mouse and left-click anywhere.
3. After that, using C-g will return the cursor to the previous mark location.

So, when `expreg-restore-point-on-quit` is `t`, as long as you haven't used C-g, the next C-g will cause the cursor to return to the `expreg mark point`.

**Comment by casouri** [comment]
No worries, I used an advice because C-g is quite special in Emacs, and other less intrusive methods like transient keymap doesn't really work for it. Advice is the most robust way IME. (I can be wrong :)

I fixed the issue by making the condition stricter so it's harder to restore point when you don't expect to. Please see if it fixes your issue.

**Comment by ISouthRain** [comment]
I don't know if this is a good thing or a bad thing. Now that I have used it for a while, there should be no problem.

But in my memory, there was still a problem after I updated `expreg`, and it may be very few times. I'm waiting for me to use it for a while.

Thank you.

**Comment by ISouthRain** [comment]
I think it should indeed have the same problem, I just triggered it once.
It's just that I can't find the reproduction step at the moment.

**Comment by ISouthRain** [comment]
a: In the same buffer.

The general situation is as follows:

1. use `expreg-expand`
2. Some operations, not sure if C-g has cancelled `expreg`
3. go to other window
4. back current window
5. C-g cursor is incorrect

Thank you for your attention, I will continue to use it for a long time to see if this problem can be reproduced.

**Comment by casouri** [comment]
No worries, I appreciate you keep working with me. I think I fixed the issue with the latest update :) Now it should be really hard to trigger the unwanted restore point behavior.
